### PR TITLE
2001 refresh

### PR DESCRIPTION
**Pull request by arnaudlh**

### CODE REVIEW

**Comment by LaurentLesle** [comment]
I have an error on the terraform validate for the example pip_simple
image

**Comment by arnaudlh** [comment]
Include issues #5 #4 #6

**Comment by arnaudlh** [comment]
> I have an error on the terraform validate for the example pip_simple
> image

Due to caf_naming convention dependency. Fixed now.

**Review by nyuen — APPROVED** [review]
GTG

**Pull request merged**
